name: .NET

on:
  push:
    branches: 
      - workflow-test
      - master
  pull_request:
    branches: 
      - workflow-test
      - master

jobs:
  build:
    environment: Env teste
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'DevProfile/appsettings.json'
      env:
        MongoConfig.Url: ${{ secrets.MONGO_URL }}
        MongoConfig.Database: ${{ secrets.MONGO_DATABASE }}
        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o devprofile 
      
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './devprofile'
